AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Customers
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  AuthLoginFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.AuthHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
            
            
  AuthLogoutFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.AuthHandler::handleLogoutRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        Logout:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post

  AuthRefreshFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.AuthHandler::handleRefreshRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        Refresh:
          Type: Api
          Properties:
            Path: /auth/refresh
            Method: post

  CreateUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.UserHandler::handleCreateUserRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: post

  GetUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.UserHandler::handleGetUserRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: get

  UpdateUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.UserHandler::handleUpdateUserRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: put

  DeleteUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.UserHandler::handleDeleteUserRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: delete

  CreateShopFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.ShopHandler::handleCreateShopRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        CreateShop:
          Type: Api
          Properties:
            Path: /shops
            Method: post

  GetShopFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.ShopHandler::handleGetShopRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        GetShop:
          Type: Api
          Properties:
            Path: /shops/{shopId}
            Method: get

  UpdateShopFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.ShopHandler::handleUpdateShopRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        UpdateShop:
          Type: Api
          Properties:
            Path: /shops/{shopId}
            Method: put

  DeleteShopFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.ShopHandler::handleDeleteShopRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        DeleteShop:
          Type: Api
          Properties:
            Path: /shops/{shopId}
            Method: delete

  CreateInvoiceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.InvoiceHandler::handleCreateInvoiceRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        CreateInvoice:
          Type: Api
          Properties:
            Path: /invoices
            Method: post

  GetInvoiceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.InvoiceHandler::handleGetInvoiceRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        GetInvoice:
          Type: Api
          Properties:
            Path: /invoices/{invoiceId}
            Method: get

  UpdateInvoiceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.InvoiceHandler::handleUpdateInvoiceRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        UpdateInvoice:
          Type: Api
          Properties:
            Path: /invoices/{invoiceId}
            Method: put

  DeleteInvoiceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.InvoiceHandler::handleDeleteInvoiceRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        DeleteInvoice:
          Type: Api
          Properties:
            Path: /invoices/{invoiceId}
            Method: delete

  GetShopHistoryFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.ims.invoice.HistoryHandler::handleGetShopHistoryRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
      Events:
        GetShopHistory:
          Type: Api
          Properties:
            Path: /shops/{shopId}/history
            Method: get
